name: acorisspos
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  flutter_inappwebview: ^6.1.5
  nfc_manager: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
